name: Deploy EastUS (JSON only)

on: workflow_dispatch

env:
  RESOURCE-GROUP: rg-eshoponweb-eastus
  LOCATION: eastus
  SUBSCRIPTION-ID: e36a3dde-b34b-42e4-aab7-f8fa0ca79452
  WEBAPP-NAME: devops-webapp-eastus-2634623321

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download published app
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download ARM template
        uses: actions/download-artifact@v4
        with:
          name: arm-template
          path: arm-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy JSON with arm-deploy (no CLI container → no Bicep)
      - name: Validate & Deploy ARM JSON
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: arm-template/webapp.json
          parameters: |
            webAppName=${{ env.WEBAPP-NAME }}
            location=${{ env.LOCATION }}
          deploymentName: eshoponweb-${{ github.run_id }}
          failOnStdErr: false
          additionalArguments: --only-show-errors

      # Push ZIP using the dedicated action (also not the CLI container)
      - name: Publish Website to WebApp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          package: .net-app/app.zip
          type: zip
